export interface AnalisisCalidad {
    id:number,
    producto:string,
    totalCamarones:number,
    observacion:string,
    color:string,
    olor:string,
    sabor:string,
    temp1:number,
    temp2:number,
    temp3:number,
    temp4:number,
    temp5:number,
    temp6:number,
    temp7:number,
    temp8:number,
    temp9:number,
    temp10:number,
    pesoMuestra:number,
    numeroCamaronesAO:number,
    grsPromedio:number,
    otros100ppm:number,
    otros10ppm:number,
    deshidratadoUni:number,
    deshidratadosPorc:number,
    blandosUni:number,
    blandosPorc :number,
    mudadosUni:number,
    mudadosPorc:number,
    cabezaBajaUni :number,
    cabezaBajaPorc:number,
    cabezaNegraUni:number,
    cabezaNegraPorc :number,
    cabezaRojaUni:number,
    cabezaRojaPorc:number,
    hepReventadoUni:number,
    hepReventadoPorc :number,
    membranaRotaUni:number,
    membranaRotaPorc:number,
    primerSegmentoUni :number,
    primerSegmentoPorc :number,
    necrosisLeveUni :number,
    necrosisLevePorc:number,
    necrosisFuerteUni :number,
    necrosisFuertePorc :number,
    melanosisUni:number,
    melanosisPorc :number,
    quebradosUni:number,
    quebradosPorc :number,
    deformesUni :number,
    deformesPorc:number,
    corbataUni:number,
    corbataPorc:number,
    pataUni:number,
    pataPorc:number,
    cascarasUni:number,
    cascarasPorc:number,
    antenasUni:number,
    antenasPorc:number,
    deterioroRUni:number,
    deterioroRPorc:number,
    totalAnalisisDef:number,
    ncamarones215:number,
    ncamarones205:number,
    ncamarones202:number,
    ncamarones195:number,
    ncamarones189:number,
    ncamarones182:number,
    ncamarones176:number,
    ncamarones169:number,
    ncamarones163:number,
    ncamarones155:number,
    ncamarones15 :number,    
    ncamarones143:number,
    ncamarones137:number, 
    ncamarones13 :number,
    ncamarones124:number, 
    ncamarones117:number, 
    ncamarones111:number, 
    ncamarones104:number, 
    ncamarones96 :number,
    ncamarones91:number,
    ncamarones85:number,
    ncamarones78:number,
    ncamarones72:number,
    ncamarones65:number,
    ncamarones59:number,
    ncamarones52:number,
    ncamarones46:number,
    ncamarones33:number,
    ncamarones26:number,
    ncamarones2:number,
    ncamarones133:number,
    ncamarones07:number,
    ncamarones39:number,
    
    totalPesosTotales:number,
    pesoT215 :number,
    pesoT205 :number,
    pesoT202 :number,
    pesoT195 :number,
    pesoT189:number,
    pesoT182 :number,
    pesoT176 :number,
    pesoT169 :number,
    pesoT163 :number,
    pesoT155:number,  
    pesoT15 :number,
    pesoT143 :number,
    pesoT137 :number,
    pesoT13  :number,
    pesoT124 :number,
    pesoT117 :number,
    pesoT111 :number,
    pesoT104 :number,
    pesoT96 :number,
    pesoT91 :number,
    pesoT85 :number,
    pesoT78 :number,
    pesoT72 :number,
    pesoT65 :number,
    pesoT59:number, 
    pesoT52:number, 
    pesoT46:number, 
    pesoT33:number, 
    pesoT26:number, 
    pesoT2 :number,
    pesoT133:number,
    pesoT07:number,
    pesoT39:number,

    totalPorcentajes:number,
    porc1:number,
    porc2:number,
    porc3:number,
    porc4:number,
    porc5:number,
    porc6:number,
    porc7:number,
    porc8:number,
    porc9:number,
    porc10:number,
    porc11:number,
    porc12:number,
    porc13:number,
    porc14:number,
    porc15:number,
    porc16:number,
    porc17:number,
    porc18:number,
    porc19:number,
    porc20:number,
    porc21:number,
    porc22:number,
    porc23:number,
    porc24:number,
    porc25:number,
    porc26:number,
    porc27:number,
    porc28:number,
    porc29:number,
    porc30:number,
    porc31:number,
    porc32:number,
    porc33:number
}